<?php

namespace Drupal\strawberryfield_clover\Plugin\Field\FieldFormatter;

use Drupal\Core\Cache\Cache;
use Drupal\Core\Field\FieldItemListInterface;
use Drupal\Core\Field\FieldItemInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Component\Utility\UrlHelper;
use Drupal\Component\Utility\NestedArray;
use Drupal\Core\Config\ConfigFactoryInterface;
use Drupal\Core\Plugin\ContainerFactoryPluginInterface;
use Drupal\Core\Entity\EntityTypeManagerInterface;
use Drupal\Core\Session\AccountInterface;
use Drupal\Core\Field\FieldDefinitionInterface;
use Drupal\format_strawberryfield\EmbargoResolverInterface;
use Drupal\format_strawberryfield\Plugin\Field\FieldFormatter\StrawberryBaseFormatter;
use Symfony\Component\DependencyInjection\ContainerInterface;

/**
 * Clover IIIF Scroll Strawberry Field formatter.
 *
 * @FieldFormatter(
 *   id = "strawberry_clover_scroll_formatter",
 *   label = @Translation("Strawberry Field Clover IIIF Scroll"),
 *   class = "\Drupal\strawberryfield_clover\Plugin\Field\FieldFormatter\StrawberryCloverScrollFormatter",
 *   field_types = {
 *     "strawberryfield_field"
 *   },
 *   quickedit = {
 *     "editor" = "disabled"
 *   }
 * )
 */
class StrawberryCloverScrollFormatter extends StrawberryBaseFormatter implements ContainerFactoryPluginInterface {

  /**
   * The entity type manager.
   *
   * @var \Drupal\Core\Entity\EntityTypeManagerInterface
   */
  protected $entityTypeManager;

  /**
   * {@inheritdoc}
   */
  public function __construct(
    $plugin_id,
    $plugin_definition,
    FieldDefinitionInterface $field_definition,
    array $settings,
    $label,
    $view_mode,
    array $third_party_settings,
    ConfigFactoryInterface $config_factory,
    AccountInterface $current_user,
    EntityTypeManagerInterface $entity_type_manager,
    EmbargoResolverInterface $embargo_resolver
  ) {
    parent::__construct(
      $plugin_id,
      $plugin_definition,
      $field_definition,
      $settings,
      $label,
      $view_mode,
      $third_party_settings,
      $config_factory,
      $embargo_resolver,
      $current_user
    );
    $this->entityTypeManager = $entity_type_manager;
  }

  /**
   * {@inheritdoc}
   */
  public static function create(
    ContainerInterface $container,
    array $configuration,
    $plugin_id,
    $plugin_definition
  ) {
    return new static(
      $plugin_id,
      $plugin_definition,
      $configuration['field_definition'],
      $configuration['settings'],
      $configuration['label'],
      $configuration['view_mode'],
      $configuration['third_party_settings'],
      $container->get('config.factory'),
      $container->get('current_user'),
      $container->get('entity_type.manager'),
      $container->get('format_strawberryfield.embargo_resolver')
    );
  }

  /**
   * {@inheritdoc}
   */
  public static function defaultSettings() {
    $settings = parent::defaultSettings();
    unset($settings['hide_on_embargo']);
    return $settings + [
      // Manifest source.
      'mediasource' => [
        'metadataexposeentity' => 'metadataexposeentity',
      ],
      'main_mediasource' => 'metadataexposeentity',
      'metadataexposeentity_source' => NULL,
      'manifesturl_json_key_source' => 'iiifmanifest',
      'manifestnodelist_json_key_source' => 'isrelatedto',
      // Width.
      'max_width' => 0,
      // Figure options.
      'figure_display' => 'image-viewer',
      'figure_aspect_ratio' => '',
      // Annotations.
      'annotations_motivations' => '',
      // Scroll offset.
      'scroll_offset' => 0,
    ];
  }

  /**
   * {@inheritdoc}
   */
  public function settingsForm(array $form, FormStateInterface $form_state) {
    $entity = NULL;
    if ($this->getSetting('metadataexposeentity_source')) {
      $entity = $this->entityTypeManager->getStorage('metadataexpose_entity')
        ->load($this->getSetting('metadataexposeentity_source'));
    }

    $options_for_mainsource = is_array($this->getSetting('mediasource')) && !empty($this->getSetting('mediasource'))
      ? $this->getSetting('mediasource')
      : self::defaultSettings()['mediasource'];

    if (($triggering_element = $form_state->getTriggeringElement()) && isset($triggering_element['#ajax']['callback'])) {
      if ($triggering_element['#ajax']['callback'][0] == get_class($this)) {
        $parents = array_slice($triggering_element['#parents'], 0, -1);
        $options_for_mainsource = $form_state->getValue($parents);
      }
    }

    $all_source_options = [
      'metadataexposeentity' => $this->t('A IIIF Manifest generated by a Metadata Display template'),
      'manifesturl' => $this->t('Strawberryfield JSON Key with one or more Manifest URLs'),
      'manifestnodelist' => $this->t('Strawberryfield JSON Key with one or more Node IDs or UUIDs'),
    ];

    $options_for_mainsource = array_filter($options_for_mainsource);
    $options_for_mainsource = array_intersect_key($options_for_mainsource, $all_source_options);

    $ajax = [
      'callback' => [get_class($this), 'ajaxCallbackMainSource'],
      'wrapper' => 'clover-scroll-main-mediasource-ajax-container',
    ];

    $default_main = ($this->getSetting('main_mediasource') && array_key_exists($this->getSetting('main_mediasource'), $options_for_mainsource))
      ? $this->getSetting('main_mediasource')
      : reset($options_for_mainsource);

    $settings_form = [

      // ----------------------------------------------------------------
      // Manifest source
      // ----------------------------------------------------------------
      'mediasource' => [
        '#type' => 'checkboxes',
        '#title' => $this->t('Source for your IIIF Manifest URLs.'),
        '#options' => $all_source_options,
        '#default_value' => $this->getSetting('mediasource') ?? [],
        '#required' => TRUE,
        '#attributes' => ['data-clover-scroll-selector' => 'mediasource'],
        '#ajax' => $ajax,
      ],
      'main_mediasource' => [
        '#type' => 'select',
        '#title' => $this->t('Select which Source will be handled as the primary one.'),
        '#options' => $options_for_mainsource,
        '#default_value' => $default_main,
        '#required' => FALSE,
        '#prefix' => '<div id="clover-scroll-main-mediasource-ajax-container">',
        '#suffix' => '</div>',
      ],
      'metadataexposeentity_source' => [
        '#type' => 'entity_autocomplete',
        '#target_type' => 'metadataexpose_entity',
        '#title' => $this->t('Select which Exposed Metadata Endpoint will generate the Manifests'),
        '#description' => $this->t('Used for Metadata Exposed Entities and Node List sources.'),
        '#selection_handler' => 'default',
        '#validate_reference' => TRUE,
        '#default_value' => $entity,
        '#states' => [
          ['visible' => [':input[data-clover-scroll-selector="mediasource"][value="metadataexposeentity"]' => ['checked' => TRUE]]],
          ['visible' => [':input[data-clover-scroll-selector="mediasource"][value="manifestnodelist"]' => ['checked' => TRUE]]],
        ],
      ],
      'manifesturl_json_key_source' => [
        '#type' => 'textfield',
        '#title' => $this->t('JSON Key from where to fetch one or more IIIF Manifest URLs.'),
        '#default_value' => $this->getSetting('manifesturl_json_key_source'),
        '#states' => [
          'visible' => [':input[data-clover-scroll-selector="mediasource"][value="manifesturl"]' => ['checked' => TRUE]],
        ],
      ],
      'manifestnodelist_json_key_source' => [
        '#type' => 'textfield',
        '#title' => $this->t('JSON Key with one or more Node IDs or UUIDs.'),
        '#default_value' => $this->getSetting('manifestnodelist_json_key_source'),
        '#states' => [
          'visible' => [':input[data-clover-scroll-selector="mediasource"][value="manifestnodelist"]' => ['checked' => TRUE]],
        ],
      ],

      // ----------------------------------------------------------------
      // Width
      // ----------------------------------------------------------------
      'max_width' => [
        '#type' => 'number',
        '#title' => $this->t('Maximum width'),
        '#description' => $this->t('Use 0 to force 100% width.'),
        '#default_value' => $this->getSetting('max_width'),
        '#size' => 5,
        '#maxlength' => 5,
        '#field_suffix' => $this->t('pixels'),
        '#min' => 0,
        '#required' => TRUE,
      ],

      // ----------------------------------------------------------------
      // Figure options
      // ----------------------------------------------------------------
      'figure_display' => [
        '#type' => 'select',
        '#title' => $this->t('Figure display (<code>options.figure.display</code>)'),
        '#description' => $this->t('How each canvas is rendered in the scroll. <em>image-viewer</em> shows a full zoomable viewer; <em>thumbnail</em> shows a smaller static image.'),
        '#options' => [
          'image-viewer' => $this->t('Image viewer (zoomable)'),
          'thumbnail' => $this->t('Thumbnail'),
        ],
        '#default_value' => $this->getSetting('figure_display'),
      ],
      'figure_aspect_ratio' => [
        '#type' => 'number',
        '#title' => $this->t('Figure aspect ratio (<code>options.figure.aspectRatio</code>)'),
        '#description' => $this->t('Numeric ratio (width ÷ height) to force for each figure, e.g. <em>0.6667</em> for 2:3. Leave 0 to use the canvas\'s natural ratio.'),
        '#default_value' => $this->getSetting('figure_aspect_ratio'),
        '#size' => 8,
        '#step' => 0.0001,
        '#min' => 0,
      ],

      // ----------------------------------------------------------------
      // Annotations
      // ----------------------------------------------------------------
      'annotations_motivations' => [
        '#type' => 'textfield',
        '#title' => $this->t('Annotation motivations filter (<code>options.annotations.motivations</code>)'),
        '#description' => $this->t('Comma-separated list of IIIF motivation values, e.g. <em>painting,supplementing</em>. Leave empty to show all.'),
        '#default_value' => $this->getSetting('annotations_motivations'),
      ],

      // ----------------------------------------------------------------
      // Scroll offset
      // ----------------------------------------------------------------
      'scroll_offset' => [
        '#type' => 'number',
        '#title' => $this->t('Scroll offset (<code>options.offset</code>)'),
        '#description' => $this->t('Pixel offset from the top when scrolling to a canvas. Useful for sticky headers.'),
        '#default_value' => $this->getSetting('scroll_offset'),
        '#size' => 5,
        '#min' => 0,
      ],

    ] + parent::settingsForm($form, $form_state);

    if (empty($options_for_mainsource)) {
      $settings_form['main_mediasource']['#empty_option'] = $this->t('- No Source selected. Please check one above. -');
    }

    return $settings_form;
  }

  /**
   * Ajax callback for mediasource checkboxes.
   */
  public static function ajaxCallbackMainSource(array $form, FormStateInterface $form_state) {
    $form_parents = $form_state->getTriggeringElement()['#array_parents'];
    $form_parents = array_slice($form_parents, 0, -2);
    $form_parents[] = 'main_mediasource';
    return NestedArray::getValue($form, $form_parents);
  }

  /**
   * {@inheritdoc}
   */
  public function settingsSummary() {
    $summary[] = $this->t('Displays IIIF content using the Clover IIIF Scroll component.');

    $main_mediasource = $this->getSetting('main_mediasource') ?: NULL;

    if ($this->getSetting('mediasource') && is_array($this->getSetting('mediasource'))) {
      foreach ($this->getSetting('mediasource') as $source => $enabled) {
        $on = (string) $enabled;
        if ($on === 'metadataexposeentity') {
          $label = '(none set)';
          if ($this->getSetting('metadataexposeentity_source')) {
            $entity = $this->entityTypeManager->getStorage('metadataexpose_entity')
              ->load($this->getSetting('metadataexposeentity_source'));
            $label = $entity ? $entity->label() : $this->getSetting('metadataexposeentity_source') . ' (missing)';
          }
          $summary[] = $this->t('Manifest from Endpoint: %label%primary', [
            '%label' => $label,
            '%primary' => ($main_mediasource === $on) ? ' (PRIMARY)' : '',
          ]);
        }
        if ($on === 'manifesturl') {
          $summary[] = $this->t('Manifest URL from JSON key: %key%primary', [
            '%key' => $this->getSetting('manifesturl_json_key_source'),
            '%primary' => ($main_mediasource === $on) ? ' (PRIMARY)' : '',
          ]);
        }
        if ($on === 'manifestnodelist') {
          $summary[] = $this->t('Node list from JSON key: %key%primary', [
            '%key' => $this->getSetting('manifestnodelist_json_key_source'),
            '%primary' => ($main_mediasource === $on) ? ' (PRIMARY)' : '',
          ]);
        }
      }
    }

    $max_width = (int) $this->getSetting('max_width');
    $summary[] = $this->t('Width: %width | Figure: %display', [
      '%width' => $max_width === 0 ? '100%' : $max_width . 'px',
      '%display' => $this->getSetting('figure_display'),
    ]);

    return array_merge($summary, parent::settingsSummary());
  }

  /**
   * {@inheritdoc}
   */
  public function viewElements(FieldItemListInterface $items, $langcode) {
    $elements = [];
    $max_width = $this->getSetting('max_width');
    $max_width_css = empty($max_width) || $max_width == 0 ? '100%' : $max_width . 'px';
    $mediasource = is_array($this->getSetting('mediasource')) ? $this->getSetting('mediasource') : [];
    $main_mediasource = $this->getSetting('main_mediasource');

    $annotations_motivations = array_values(array_filter(
      array_map('trim', explode(',', $this->getSetting('annotations_motivations') ?? ''))
    ));

    $figure_aspect_ratio = (float) $this->getSetting('figure_aspect_ratio');

    $embargo_context = [];
    $embargo_tags = [];
    $embargo_info = [];

    $nodeuuid = $items->getEntity()->uuid();

    foreach ($items as $delta => $item) {
      $main_property = $item->getFieldDefinition()
        ->getFieldStorageDefinition()
        ->getMainPropertyName();
      $value = $item->{$main_property};
      if (empty($value)) {
        continue;
      }

      $jsondata = json_decode($item->value, TRUE);
      if (json_last_error() !== JSON_ERROR_NONE) {
        return ['#markup' => $this->t('ERROR: could not decode Strawberry field JSON.')];
      }

      $manifests = [];
      foreach ($mediasource as $iiifsource) {
        switch ((string) $iiifsource) {
          case 'metadataexposeentity':
            $manifests['metadataexposeentity'] = $this->processManifestforMetadataExposeEntity($jsondata, $item);
            break;
          case 'manifesturl':
            $manifests['manifesturl'] = $this->processManifestforURL($jsondata, $item);
            break;
          case 'manifestnodelist':
            $manifests['manifestnodelist'] = $this->processManifestforNodeList($jsondata, $item);
            break;
        }
      }

      if (isset($manifests[$main_mediasource]) && !empty($manifests[$main_mediasource])) {
        $main_manifesturl = array_shift($manifests[$main_mediasource]);
      }
      else {
        $all_manifesturl = array_reduce($manifests, 'array_merge', []);
        $main_manifesturl = array_shift($all_manifesturl);
      }

      if (!empty($main_manifesturl)) {
        $htmlid = 'iiif-' . $item->getName() . '-' . $nodeuuid . '-' . $delta . '-clover-scroll';

        $elements[$delta]['media'] = [
          '#type' => 'container',
          '#default_value' => $htmlid,
          '#attributes' => [
            'id' => $htmlid,
            'class' => ['strawberry-clover-scroll-item', 'field-iiif'],
            'style' => "width:{$max_width_css}",
            'data-iiif-infojson' => '',
          ],
        ];

        $scroll_settings = [
          'nodeuuid' => $nodeuuid,
          'manifesturl' => $main_manifesturl,
          'width' => $max_width_css,
          'figure_display' => $this->getSetting('figure_display'),
          'figure_aspect_ratio' => $figure_aspect_ratio > 0 ? $figure_aspect_ratio : NULL,
          'annotations_motivations' => $annotations_motivations,
          'scroll_offset' => (int) $this->getSetting('scroll_offset'),
        ];

        $elements[$delta]['media']['#attached']['drupalSettings']['format_strawberryfield']['clover_scroll'][$htmlid] = $scroll_settings;
        $elements[$delta]['#attached']['library'][] = 'strawberryfield_clover/clover_scroll';
      }

      if (empty($elements[$delta])) {
        $elements[$delta] = [
          '#markup' => '<i class="d-none field-iiif-no-viewer"></i>',
          '#prefix' => '<span>',
          '#suffix' => '</span>',
        ];
      }

      if (isset($item->_attributes)) {
        $elements[$delta] += ['#attributes' => []];
        $elements[$delta]['#attributes'] += $item->_attributes;
        unset($item->_attributes);
      }

      if (isset($elements[$delta]['#attributes']) && empty($elements[$delta]['#attributes'])) {
        unset($elements[$delta]['#attributes']);
      }
    }

    $elements['#cache'] = [
      'context' => Cache::mergeContexts(
        $items->getEntity()->getCacheContexts(),
        ['user.permissions', 'user.roles'],
        $embargo_context
      ),
      'tags' => Cache::mergeTags(
        $items->getEntity()->getCacheTags(),
        $embargo_tags,
        ['config:format_strawberryfield.embargo_settings']
      ),
    ];

    return $elements;
  }

  /**
   * Decodes a JSON textarea setting, returning the decoded value or NULL.
   */
  protected function parseJsonSetting(string $key) {
    $raw = trim($this->getSetting($key) ?? '');
    if (empty($raw)) {
      return NULL;
    }
    $decoded = json_decode($raw, TRUE);
    return json_last_error() === JSON_ERROR_NONE ? $decoded : NULL;
  }

  /**
   * Generates a Manifest URL from a Metadata Expose Entity for the current node.
   */
  public function processManifestforMetadataExposeEntity(array $jsondata, FieldItemInterface $item) {
    $manifests = [];
    $nodeuuid = $item->getEntity()->uuid();
    if ($this->getSetting('metadataexposeentity_source')) {
      $entity = $this->entityTypeManager->getStorage('metadataexpose_entity')
        ->load($this->getSetting('metadataexposeentity_source'));
      if ($entity) {
        $manifests[] = $entity->getUrlForItemFromNodeUUID($nodeuuid, TRUE);
      }
    }
    return $manifests;
  }

  /**
   * Fetches Manifest URLs from a JSON Key.
   */
  public function processManifestforURL(array $jsondata, FieldItemInterface $item) {
    $manifests = [];
    $jsonkey = $this->getSetting('manifesturl_json_key_source');
    if ($jsonkey && isset($jsondata[$jsonkey])) {
      $urls = is_array($jsondata[$jsonkey]) ? $jsondata[$jsonkey] : [$jsondata[$jsonkey]];
      foreach ($urls as $url) {
        if (is_string($url) && UrlHelper::isValid($url, TRUE)) {
          $manifests[] = $url;
        }
      }
    }
    return $manifests;
  }

  /**
   * Generates Manifest URLs from a JSON Key containing Node IDs or UUIDs.
   */
  public function processManifestforNodeList(array $jsondata, FieldItemInterface $item) {
    $manifests = [];
    $jsonkey = $this->getSetting('manifestnodelist_json_key_source');
    if (!$jsonkey || !$this->getSetting('metadataexposeentity_source')) {
      return $manifests;
    }
    $entity = $this->entityTypeManager->getStorage('metadataexpose_entity')
      ->load($this->getSetting('metadataexposeentity_source'));
    if (!$entity || !isset($jsondata[$jsonkey])) {
      return $manifests;
    }
    $nodelist = is_array($jsondata[$jsonkey]) ? $jsondata[$jsonkey] : [$jsondata[$jsonkey]];
    $cleannodelist = array_filter($nodelist, 'is_integer');
    $access_manager = \Drupal::service('access_manager');
    foreach ($this->entityTypeManager->getStorage('node')->loadMultiple($cleannodelist) as $node) {
      $has_access = $access_manager->checkNamedRoute(
        'format_strawberryfield.metadatadisplay_caster',
        [
          'node' => $node->uuid(),
          'metadataexposeconfig_entity' => $entity->id(),
          'format' => 'manifest.jsonld',
        ],
        $this->currentUser
      );
      if ($has_access) {
        $manifests[] = $entity->getUrlForItemFromNodeUUID($node->uuid(), TRUE);
      }
    }
    return $manifests;
  }

}
