<?php

namespace Drupal\strawberryfield_clover\Plugin\Field\FieldFormatter;

use Drupal\Core\Cache\Cache;
use Drupal\Core\Field\FieldItemListInterface;
use Drupal\Core\Field\FieldItemInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Component\Utility\UrlHelper;
use Drupal\Core\Config\ConfigFactoryInterface;
use Drupal\Core\Plugin\ContainerFactoryPluginInterface;
use Drupal\Core\Entity\EntityTypeManagerInterface;
use Drupal\Core\Session\AccountInterface;
use Drupal\Core\Field\FieldDefinitionInterface;
use Drupal\format_strawberryfield\EmbargoResolverInterface;
use Drupal\format_strawberryfield\Plugin\Field\FieldFormatter\StrawberryBaseFormatter;
use Symfony\Component\DependencyInjection\ContainerInterface;

/**
 * Clover IIIF Slider Strawberry Field formatter.
 *
 * Renders a IIIF Collection as a horizontally scrolling Swiper carousel.
 * The iiifContent prop must point to a IIIF Collection manifest; use a
 * Metadata Display endpoint that outputs a Collection, or store a
 * Collection URL directly in a Strawberry Field JSON key.
 *
 * @FieldFormatter(
 *   id = "strawberry_clover_slider_formatter",
 *   label = @Translation("Strawberry Field Clover IIIF Slider"),
 *   class = "\Drupal\strawberryfield_clover\Plugin\Field\FieldFormatter\StrawberryCloverSliderFormatter",
 *   field_types = {
 *     "strawberryfield_field"
 *   },
 *   quickedit = {
 *     "editor" = "disabled"
 *   }
 * )
 */
class StrawberryCloverSliderFormatter extends StrawberryBaseFormatter implements ContainerFactoryPluginInterface {

  /**
   * The entity type manager.
   *
   * @var \Drupal\Core\Entity\EntityTypeManagerInterface
   */
  protected $entityTypeManager;

  /**
   * {@inheritdoc}
   */
  public function __construct(
    $plugin_id,
    $plugin_definition,
    FieldDefinitionInterface $field_definition,
    array $settings,
    $label,
    $view_mode,
    array $third_party_settings,
    ConfigFactoryInterface $config_factory,
    AccountInterface $current_user,
    EntityTypeManagerInterface $entity_type_manager,
    EmbargoResolverInterface $embargo_resolver
  ) {
    parent::__construct(
      $plugin_id,
      $plugin_definition,
      $field_definition,
      $settings,
      $label,
      $view_mode,
      $third_party_settings,
      $config_factory,
      $embargo_resolver,
      $current_user
    );
    $this->entityTypeManager = $entity_type_manager;
  }

  public static function create(
    ContainerInterface $container,
    array $configuration,
    $plugin_id,
    $plugin_definition
  ) {
    return new static(
      $plugin_id,
      $plugin_definition,
      $configuration['field_definition'],
      $configuration['settings'],
      $configuration['label'],
      $configuration['view_mode'],
      $configuration['third_party_settings'],
      $container->get('config.factory'),
      $container->get('current_user'),
      $container->get('entity_type.manager'),
      $container->get('format_strawberryfield.embargo_resolver')
    );
  }

  public static function defaultSettings() {
    $settings = parent::defaultSettings();
    unset($settings['hide_on_embargo']);
    return $settings + [
      'mediasource' => [
        'metadataexposeentity' => 'metadataexposeentity',
      ],
      'main_mediasource' => 'metadataexposeentity',
      'metadataexposeentity_source' => NULL,
      'manifesturl_json_key_source' => 'iiifcollection',
      'max_width' => 0,
      'credentials' => 'omit',
      'custom_view_all' => '',
    ];
  }

  public function settingsForm(array $form, FormStateInterface $form_state) {
    $entity = NULL;
    if ($this->getSetting('metadataexposeentity_source')) {
      $entity = $this->entityTypeManager->getStorage('metadataexpose_entity')
        ->load($this->getSetting('metadataexposeentity_source'));
    }

    $options_for_mainsource = is_array($this->getSetting('mediasource')) && !empty($this->getSetting('mediasource'))
      ? $this->getSetting('mediasource')
      : self::defaultSettings()['mediasource'];

    if (($triggering_element = $form_state->getTriggeringElement()) && isset($triggering_element['#ajax']['callback'])) {
      if ($triggering_element['#ajax']['callback'][0] == get_class($this)) {
        $parents = array_slice($triggering_element['#parents'], 0, -1);
        $options_for_mainsource = $form_state->getValue($parents);
      }
    }

    $all_source_options = [
      'metadataexposeentity' => $this->t('A IIIF Collection generated by a Metadata Display template'),
      'manifesturl' => $this->t('Strawberryfield JSON Key with a Collection URL'),
    ];

    $options_for_mainsource = array_filter($options_for_mainsource);
    $options_for_mainsource = array_intersect_key($options_for_mainsource, $all_source_options);

    $ajax = [
      'callback' => [get_class($this), 'ajaxCallbackMainSource'],
      'wrapper' => 'clover-slider-main-mediasource-ajax-container',
    ];

    $default_main = ($this->getSetting('main_mediasource') && array_key_exists($this->getSetting('main_mediasource'), $options_for_mainsource))
      ? $this->getSetting('main_mediasource')
      : reset($options_for_mainsource);

    $settings_form = [

      'mediasource' => [
        '#type' => 'checkboxes',
        '#title' => $this->t('Source for your IIIF Collection URL.'),
        '#description' => $this->t('The Clover Slider requires a IIIF Collection manifest (not a single item Manifest). Ensure your Metadata Display template or JSON key outputs a Collection.'),
        '#options' => $all_source_options,
        '#default_value' => $this->getSetting('mediasource') ?? [],
        '#required' => TRUE,
        '#attributes' => ['data-clover-slider-selector' => 'mediasource'],
        '#ajax' => $ajax,
      ],
      'main_mediasource' => [
        '#type' => 'select',
        '#title' => $this->t('Select which Source will be handled as the primary one.'),
        '#options' => $options_for_mainsource,
        '#default_value' => $default_main,
        '#required' => FALSE,
        '#prefix' => '<div id="clover-slider-main-mediasource-ajax-container">',
        '#suffix' => '</div>',
      ],
      'metadataexposeentity_source' => [
        '#type' => 'entity_autocomplete',
        '#target_type' => 'metadataexpose_entity',
        '#title' => $this->t('Select which Exposed Metadata Endpoint will generate the Collection'),
        '#description' => $this->t('The endpoint must render a IIIF Collection manifest (type "Collection").'),
        '#selection_handler' => 'default',
        '#validate_reference' => TRUE,
        '#default_value' => $entity,
        '#states' => [
          'visible' => [':input[data-clover-slider-selector="mediasource"][value="metadataexposeentity"]' => ['checked' => TRUE]],
        ],
      ],
      'manifesturl_json_key_source' => [
        '#type' => 'textfield',
        '#title' => $this->t('JSON Key containing the IIIF Collection URL.'),
        '#default_value' => $this->getSetting('manifesturl_json_key_source'),
        '#states' => [
          'visible' => [':input[data-clover-slider-selector="mediasource"][value="manifesturl"]' => ['checked' => TRUE]],
        ],
      ],

      'max_width' => [
        '#type' => 'number',
        '#title' => $this->t('Maximum width'),
        '#description' => $this->t('Use 0 to force 100% width.'),
        '#default_value' => $this->getSetting('max_width'),
        '#size' => 5,
        '#maxlength' => 5,
        '#field_suffix' => $this->t('pixels'),
        '#min' => 0,
        '#required' => TRUE,
      ],

      'credentials' => [
        '#type' => 'select',
        '#title' => $this->t('Fetch credentials (<code>options.credentials</code>)'),
        '#options' => [
          'omit' => $this->t('omit (default)'),
          'same-origin' => $this->t('same-origin'),
          'include' => $this->t('include'),
        ],
        '#default_value' => $this->getSetting('credentials'),
      ],
      'custom_view_all' => [
        '#type' => 'textfield',
        '#title' => $this->t('Custom "View all" link (<code>options.customViewAll</code>)'),
        '#description' => $this->t('URL to use for the "View all" link that appears at the end of the slider. Leave empty for default behavior.'),
        '#default_value' => $this->getSetting('custom_view_all'),
      ],

    ] + parent::settingsForm($form, $form_state);

    if (empty($options_for_mainsource)) {
      $settings_form['main_mediasource']['#empty_option'] = $this->t('- No Source selected. Please check one above. -');
    }

    return $settings_form;
  }

  /**
   * Add an Ajax callback
   */
  public static function ajaxCallbackMainSource(array $form, FormStateInterface $form_state) {
    $form_parents = $form_state->getTriggeringElement()['#array_parents'];
    $form_parents = array_slice($form_parents, 0, -2);
    $form_parents[] = 'main_mediasource';
    return NestedArray::getValue($form, $form_parents);
  }

  public function settingsSummary() {
    $summary[] = $this->t('Displays a IIIF Collection using the Clover IIIF Slider component.');

    $main_mediasource = $this->getSetting('main_mediasource') ?: NULL;

    if ($this->getSetting('mediasource') && is_array($this->getSetting('mediasource'))) {
      foreach ($this->getSetting('mediasource') as $source => $enabled) {
        $on = (string) $enabled;
        if ($on === 'metadataexposeentity') {
          $label = '(none set)';
          if ($this->getSetting('metadataexposeentity_source')) {
            $entity = $this->entityTypeManager->getStorage('metadataexpose_entity')
              ->load($this->getSetting('metadataexposeentity_source'));
            $label = $entity ? $entity->label() : $this->getSetting('metadataexposeentity_source') . ' (missing)';
          }
          $summary[] = $this->t('Collection from Endpoint: %label%primary', [
            '%label' => $label,
            '%primary' => ($main_mediasource === $on) ? ' (PRIMARY)' : '',
          ]);
        }
        if ($on === 'manifesturl') {
          $summary[] = $this->t('Collection URL from JSON key: %key%primary', [
            '%key' => $this->getSetting('manifesturl_json_key_source'),
            '%primary' => ($main_mediasource === $on) ? ' (PRIMARY)' : '',
          ]);
        }
      }
    }

    $max_width = (int) $this->getSetting('max_width');
    $summary[] = $this->t('Width: %width | Credentials: %creds', [
      '%width' => $max_width === 0 ? '100%' : $max_width . 'px',
      '%creds' => $this->getSetting('credentials'),
    ]);

    return array_merge($summary, parent::settingsSummary());
  }

  public function viewElements(FieldItemListInterface $items, $langcode) {
    $elements = [];
    $max_width = $this->getSetting('max_width');
    $max_width_css = empty($max_width) || $max_width == 0 ? '100%' : $max_width . 'px';
    $mediasource = is_array($this->getSetting('mediasource')) ? $this->getSetting('mediasource') : [];
    $main_mediasource = $this->getSetting('main_mediasource');

    $embargo_context = [];
    $embargo_tags = [];

    $nodeuuid = $items->getEntity()->uuid();

    foreach ($items as $delta => $item) {
      $main_property = $item->getFieldDefinition()
        ->getFieldStorageDefinition()
        ->getMainPropertyName();
      $value = $item->{$main_property};
      if (empty($value)) {
        continue;
      }

      $jsondata = json_decode($item->value, TRUE);
      if (json_last_error() !== JSON_ERROR_NONE) {
        return ['#markup' => $this->t('ERROR: could not decode Strawberry field JSON.')];
      }

      $collections = [];
      foreach ($mediasource as $iiifsource) {
        switch ((string) $iiifsource) {
          case 'metadataexposeentity':
            $collections['metadataexposeentity'] = $this->processManifestforMetadataExposeEntity($jsondata, $item);
            break;
          case 'manifesturl':
            $collections['manifesturl'] = $this->processManifestforURL($jsondata, $item);
            break;
        }
      }

      if (isset($collections[$main_mediasource]) && !empty($collections[$main_mediasource])) {
        $collection_url = array_shift($collections[$main_mediasource]);
      }
      else {
        $all_collections = array_reduce($collections, 'array_merge', []);
        $collection_url = array_shift($all_collections);
      }

      if (!empty($collection_url)) {
        $htmlid = 'iiif-' . $item->getName() . '-' . $nodeuuid . '-' . $delta . '-clover-slider';

        $elements[$delta]['media'] = [
          '#type' => 'container',
          '#default_value' => $htmlid,
          '#attributes' => [
            'id' => $htmlid,
            'class' => ['strawberry-clover-slider-item', 'field-iiif'],
            'style' => "width:{$max_width_css}",
            'data-iiif-infojson' => '',
          ],
        ];

        $slider_settings = [
          'nodeuuid' => $nodeuuid,
          'collectionurl' => $collection_url,
          'width' => $max_width_css,
          'credentials' => $this->getSetting('credentials'),
          'custom_view_all' => $this->getSetting('custom_view_all') ?: NULL,
        ];

        $elements[$delta]['media']['#attached']['drupalSettings']['format_strawberryfield']['clover_slider'][$htmlid] = $slider_settings;
        $elements[$delta]['#attached']['library'][] = 'strawberryfield_clover/clover_slider';
      }

      if (empty($elements[$delta])) {
        $elements[$delta] = [
          '#markup' => '<i class="d-none field-iiif-no-viewer"></i>',
          '#prefix' => '<span>',
          '#suffix' => '</span>',
        ];
      }

      if (isset($item->_attributes)) {
        $elements[$delta] += ['#attributes' => []];
        $elements[$delta]['#attributes'] += $item->_attributes;
        unset($item->_attributes);
      }

      if (isset($elements[$delta]['#attributes']) && empty($elements[$delta]['#attributes'])) {
        unset($elements[$delta]['#attributes']);
      }
    }

    $elements['#cache'] = [
      'context' => Cache::mergeContexts(
        $items->getEntity()->getCacheContexts(),
        ['user.permissions', 'user.roles'],
        $embargo_context
      ),
      'tags' => Cache::mergeTags(
        $items->getEntity()->getCacheTags(),
        $embargo_tags,
        ['config:format_strawberryfield.embargo_settings']
      ),
    ];

    return $elements;
  }

  /**
   * Generates a Collection URL from a Metadata Expose Entity for the current node.
   */
  public function processManifestforMetadataExposeEntity(array $jsondata, FieldItemInterface $item) {
    $collections = [];
    $nodeuuid = $item->getEntity()->uuid();
    if ($this->getSetting('metadataexposeentity_source')) {
      $entity = $this->entityTypeManager->getStorage('metadataexpose_entity')
        ->load($this->getSetting('metadataexposeentity_source'));
      if ($entity) {
        $collections[] = $entity->getUrlForItemFromNodeUUID($nodeuuid, TRUE);
      }
    }
    return $collections;
  }

  /**
   * Fetches a Collection URL from a JSON Key.
   */
  public function processManifestforURL(array $jsondata, FieldItemInterface $item) {
    $collections = [];
    $jsonkey = $this->getSetting('manifesturl_json_key_source');
    if ($jsonkey && isset($jsondata[$jsonkey])) {
      $urls = is_array($jsondata[$jsonkey]) ? $jsondata[$jsonkey] : [$jsondata[$jsonkey]];
      foreach ($urls as $url) {
        if (is_string($url) && UrlHelper::isValid($url, TRUE)) {
          $collections[] = $url;
        }
      }
    }
    return $collections;
  }

}
